# Fine-tuning configuration for RedEx 

train:
  num_epochs: 500
  lr: 0.002746             
  weight_decay: 2.41e-5
  patience: 30
  task: regression
  seed: 42
  batch_size: 64

freeze:
  strategy: top_layers   
  freeze_ratio: 0.5       # proportion of conv layers to freeze

model:
  
  dropout: 0.053

cv:
  n_folds: 5
  test_ratio: 0.2
